apiVersion: v1
kind: Service
metadata:
  name: {{ include "nova-stack.fullname" . }}-api
  labels:
    {{- include "nova-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "nova-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
