apiVersion: v1
kind: Secret
metadata:
  name: nova-api-secrets
  namespace: nova-staging
type: Opaque
stringData:
  database-url: postgres://rms_app:Owner%40123@postgres:5432/rms_dev
  redis-url: redis://redis:6379
  jwt-secret: local-staging-jwt-secret-please-rotate-123456
  refresh-token-secret: local-staging-refresh-secret-please-rotate-654321
---
apiVersion: v1
kind: Secret
metadata:
  name: nova-worker-secrets
  namespace: nova-staging
type: Opaque
stringData:
  database-url: postgres://rms_app:Owner%40123@postgres:5432/rms_dev
  redis-url: redis://redis:6379


